### ISSUE TITLE
Dependency nix needs to be updated

### ISSUE THREAD

**Issue by Efreak** [dubrowgn/tcalc#14]
nix 0.7 is specified as a dependency of tcalc-rustyline. This package doesn't build on Android using rustic 1.56.1.

```
❯ cargo install tcalc
    Updating crates.io index
  Installing tcalc v1.7.16
   Compiling libc v0.2.107
   Compiling semver v0.1.20
   Compiling cfg-if v0.1.10
   Compiling bitflags v0.4.0
   Compiling void v1.0.2
   Compiling encode_unicode v0.1.3
   Compiling unicode-width v0.1.9
   Compiling rustc_version v0.1.7
   Compiling nix v0.7.0
   Compiling dirs-sys v0.3.6
   Compiling dirs v2.0.2
error[E0518]: attribute should be applied to function or closure
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.7.0/src/sys/termios.rs:42:5
   |
42 |       #[inline]
   |       ^^^^^^^^^
43 |       #[cfg(all(target_os = "android", not(target_arch = "mips")))]
44 | /     mod android {
45 | |         use libc;
46 | |         use libc::c_int;
47 | |         use super::consts::*;
...  |
90 | |         }
91 | |     }
   | |_____- not a function or closure

For more information about this error, try `rustc --explain E0518`.
error: failed to compile `tcalc v1.7.16`, intermediate artifacts can be found at `/data/data/com.termux/files/usr/tmp/cargo-installT9AStZ`

Caused by:
  could not compile `nix` due to previous error

~/src/cargo took 6s
```

**Comment by dubrowgn** [comment]
Thanks for the report. I've been thinking about migrating to https://crates.io/crates/reedline, since the keybindings appear to be customizable. This would avoid the need to maintain a fork of rustyline.

Also, sorry for the (very) late response. I somehow missed this originally :(
